#line 1 "flexer.c"

#line 3 "flexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[166] =
    {   0,
        0,    0,   46,   44,   43,   42,   44,   44,   27,   38,
       28,   29,   25,   23,   34,   24,   44,   26,   41,   41,
       44,   17,   21,   19,   40,   32,   33,   40,   40,   40,
       40,   40,   40,   40,   30,   31,   43,   42,   16,    0,
       41,   41,   41,   41,    0,    0,    0,    0,    0,   41,
       41,   22,   18,   15,   20,   40,   40,   40,   40,   40,
       40,   40,   40,    5,   40,   40,   40,   40,   40,   41,
        0,   41,   41,    0,   41,   41,   41,    0,    0,   41,
       41,    0,   41,   41,   40,   40,   40,   40,   40,   40,
        7,   40,    1,   40,   40,   40,   40,    8,    0,   41,

       41,   41,    0,   41,   41,   41,   41,   41,   41,    0,
       41,    0,   41,   41,   40,   39,    6,   40,   40,    0,
        9,   10,   40,   35,   40,   40,   41,   41,   41,   41,
        0,    0,   41,   40,   40,    2,    0,    0,   40,   40,
       40,    0,    0,   41,   41,   40,   40,    0,    0,   40,
        3,    4,   14,   36,    0,    0,   40,    0,   11,   40,
       12,   37,    0,   13,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,    1,   22,
       23,   24,    1,    1,   25,   26,   25,   25,   27,   25,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   29,
       28,   28,   30,   28,   28,   28,   28,   31,   28,   28,
       32,    1,   33,    1,   34,    1,   35,   26,   36,   25,

       37,   38,   39,   28,   40,   28,   28,   41,   42,   43,
       44,   45,   28,   46,   47,   48,   49,   50,   28,   51,
       28,   28,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    1,    2,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    4,    4,    4,    5,    6,    5,
        5,    1,    1,    7,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    6,    5,    5,    5,    5,    5,
        5,    1,    1
    } ;

static const flex_int16_t yy_base[172] =
    {   0,
        0,    0,  401,  402,   52,  397,  376,  392,  402,  402,
      402,  402,  402,  402,  402,  402,   40,  402,   46,   83,
      374,  373,  370,  367,    0,  402,  402,  351,   27,   40,
       24,  347,   31,  346,  402,  402,   72,  368,  402,  362,
      402,   87,  108,  131,  137,   53,   74,  333,  152,  175,
      181,  402,  402,  402,  402,    0,  317,   68,  327,  319,
      295,  286,  287,    0,  281,  268,  270,   65,  244,  186,
      119,  197,  202,  163,  213,  123,   78,  101,  142,  224,
      220,  255,    0,  167,  240,  248,  243,  243,  243,  260,
        0,  230,    0,  221,  228,  212,   50,    0,  228,  242,

      250,  254,  265,  275,  208,  105,  112,  279,  283,   87,
      289,  293,    0,  297,  216,    0,    0,  206,  205,  114,
        0,    0,  204,    0,  208,  202,  302,  307,  318,  322,
      299,  328,  332,  195,  163,    0,  164,  171,  149,  152,
      140,  324,    0,  337,  342,  133,  141,  133,  131,  123,
        0,    0,    0,    0,  110,  104,   92,   65,  402,   40,
       34,    0,   12,  402,  402,  368,  372,  376,  381,  385,
      388
    } ;

static const flex_int16_t yy_def[172] =
    {   0,
      165,    1,  165,  165,  165,  165,  165,  166,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  167,  165,  165,  167,  167,  167,
      167,  167,  167,  167,  165,  165,  165,  165,  165,  166,
      165,  165,  165,  165,  165,  165,  165,  168,  165,  165,
      165,  165,  165,  165,  165,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      169,  168,   50,  165,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  165,  165,

      165,  165,  165,  165,  165,  165,  165,  165,  165,  170,
      169,  165,  111,  165,  167,  167,  167,  167,  167,  165,
      167,  167,  167,  167,  167,  167,  165,  165,  165,  165,
      171,  165,  165,  167,  167,  167,  165,  165,  167,  167,
      167,  171,  142,  165,  165,  167,  167,  165,  165,  167,
      167,  167,  167,  167,  165,  165,  167,  165,  165,  167,
      165,  167,  165,  165,    0,  165,  165,  165,  165,  165,
      165
    } ;

static const flex_int16_t yy_nxt[456] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       21,   22,   23,   24,   25,   25,   25,   25,   25,   25,
       25,   26,   27,   25,   25,   28,   29,   30,   25,   31,
       25,   32,   25,   25,   25,   25,   33,   25,   25,   34,
       25,   35,   36,   37,  164,   37,   42,   42,   42,   42,
       43,   64,   44,   44,   44,   45,   65,   58,   67,   77,
       77,   46,   47,   37,  163,   37,   48,   59,   68,   49,
       60,   61,   47,   62,  162,   79,   78,   79,   63,  125,
       80,   80,   80,   80,  106,  106,   48,   43,  126,   50,

       50,   50,   50,   70,   70,   70,   70,   86,   96,   47,
       97,  107,  161,   71,   87,  112,   51,   77,   77,   47,
       72,  106,  106,   71,   73,   73,   73,   73,  106,  106,
       99,  112,   99,  160,   74,  100,  100,  100,  100,  105,
      105,  105,  137,  138,   74,   43,  159,   75,   75,   75,
       45,   43,  158,   45,   45,   45,   45,   47,   80,   80,
       80,   80,  157,   47,   76,  156,   43,   47,   44,   44,
       44,   45,  155,   47,  103,  154,  103,  153,   47,  104,
      104,  104,  104,  114,  114,  114,  114,  152,   47,   43,
      151,   83,   83,   83,   83,   43,  150,   50,   50,   50,

       50,   47,   70,   70,   70,   70,  149,   47,   84,  148,
      147,   47,   71,   70,   70,   70,   70,   47,  101,  101,
      101,  101,   71,   71,  105,  105,  105,   43,   74,   75,
       75,   75,   45,   71,  110,  102,  146,  141,   74,   47,
      108,  108,  108,  108,  100,  100,  100,  100,  112,   47,
      140,  139,  136,  113,  135,  134,  124,  109,  127,  127,
      127,  127,  123,  122,  112,  121,  101,  101,  101,  101,
      101,  101,  101,  101,  120,  128,   74,  119,  118,  117,
       74,  104,  104,  104,  104,  116,   74,  115,  165,   98,
       74,  129,  129,  129,  129,  108,  108,  108,  108,  108,

      108,  108,  108,  110,  132,   95,  132,   94,  130,  133,
      133,  133,  133,  114,  114,  114,  114,  112,  127,  127,
      127,  127,  165,  127,  127,  127,  127,  112,   93,   92,
       84,   91,  143,  112,  129,  129,  129,  129,  129,  129,
      129,  129,   90,  112,  133,  133,  133,  133,  144,  144,
      144,  144,  112,  144,  144,  144,  144,  165,  144,  144,
      144,  144,   89,   88,   85,  145,   82,   41,  112,   40,
       38,   40,   40,   40,   40,   56,   56,   56,   56,   81,
       69,   66,   81,  111,  111,   57,  111,  111,  131,   55,
      131,  142,   54,  142,  142,   53,   52,   41,   39,   38,

      165,    3,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165
    } ;

static const flex_int16_t yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,  163,    5,   17,   17,   17,   17,
       19,   31,   19,   19,   19,   19,   31,   29,   33,   46,
       46,   19,   19,   37,  161,   37,   19,   29,   33,   19,
       30,   30,   19,   30,  160,   47,   46,   47,   30,   97,
       47,   47,   47,   47,   77,   77,   19,   20,   97,   20,

       20,   20,   20,   42,   42,   42,   42,   58,   68,   20,
       68,   77,  158,   42,   58,  110,   20,   78,   78,   20,
       42,  106,  106,   42,   43,   43,   43,   43,  107,  107,
       71,  110,   71,  157,   43,   71,   71,   71,   71,   76,
       76,   76,  120,  120,   43,   44,  156,   44,   44,   44,
       44,   45,  155,   45,   45,   45,   45,   44,   79,   79,
       79,   79,  150,   45,   44,  149,   49,   44,   49,   49,
       49,   49,  148,   45,   74,  147,   74,  146,   49,   74,
       74,   74,   74,   84,   84,   84,   84,  141,   49,   50,
      140,   50,   50,   50,   50,   51,  139,   51,   51,   51,

       51,   50,   70,   70,   70,   70,  138,   51,   50,  137,
      135,   50,   70,   72,   72,   72,   72,   51,   73,   73,
       73,   73,   70,   72,  105,  105,  105,   75,   73,   75,
       75,   75,   75,   72,   81,   73,  134,  126,   73,   75,
       80,   80,   80,   80,   99,   99,   99,   99,   81,   75,
      125,  123,  119,   81,  118,  115,   96,   80,  100,  100,
      100,  100,   95,   94,   81,   92,  101,  101,  101,  101,
      102,  102,  102,  102,   90,  100,  101,   89,   88,   87,
      102,  103,  103,  103,  103,   86,  101,   85,   82,   69,
      102,  104,  104,  104,  104,  108,  108,  108,  108,  109,

      109,  109,  109,  111,  112,   67,  112,   66,  104,  112,
      112,  112,  112,  114,  114,  114,  114,  111,  127,  127,
      127,  127,  111,  128,  128,  128,  128,  131,   65,   63,
      114,   62,  131,  111,  129,  129,  129,  129,  130,  130,
      130,  130,   61,  131,  132,  132,  132,  132,  133,  133,
      133,  133,  142,  144,  144,  144,  144,  142,  145,  145,
      145,  145,   60,   59,   57,  133,   48,   40,  142,  166,
       38,  166,  166,  166,  166,  167,  167,  167,  167,  168,
       34,   32,  168,  169,  169,   28,  169,  169,  170,   24,
      170,  171,   23,  171,  171,   22,   21,    8,    7,    6,

        3,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[45] =
    {   0,
      175,  184,  193,  202,  211,  220,  229,  238,  247,  256,
      265,  274,  283,  292,  301,  310,  319,  328,  337,  346,
      355,  364,  373,  382,  391,  400,  409,  418,  427,  436,
      445,  454,  463,  472,  481,  490,  499,  508,  517,  526,
      534,  542,  553,  555
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\flexer.l"
#line 2 ".\\flexer.l"
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "flexer.h"
#include "bisoner.h"

extern Analyzer *analyzer;
extern bool hasErrors;
extern bool lastTokenWasSeparator;
extern int ts_id;
extern int ts_const;
extern int fip_pos;
extern int exceptions_pos;
extern uint32_t currLine;

void add_TS_ID(Analyzer *analyzer, const char *name, int *ts_id)
{
    int* value = (int*)ht_get(analyzer->TS_ID, name);

    if (value == NULL) {
        TS_Entry *entry = (TS_Entry*)malloc(sizeof(TS_Entry));

        entry->id = *ts_id;
        entry->name = strdup(name);

        ht_set(analyzer->TS_ID, name, entry);
        (*ts_id)++;  // Increment the global counter
    }
}

void add_TS_CONST(Analyzer *analyzer, const char* name, int *ts_const)
{
    int* value = (int*)ht_get(analyzer->TS_CONST, name);

    if (value == NULL) {
        TS_Entry *entry = (TS_Entry*)malloc(sizeof(TS_Entry));

        entry->id = *ts_const;
        entry->name = strdup(name);

        ht_set(analyzer->TS_CONST, name, entry);
        (*ts_const)++;  // Increment the global counter
    }
}

void add_FIP_Entry(Analyzer *analyzer, int keyword_id, const char* keyword, int *ts_pos)
{
    FIP_Entry entry;
    entry.keyword_id = keyword_id;
    entry.keyword = keyword;
    entry.ts_pos = *ts_pos;

    analyzer->FIP[fip_pos++] = entry;
}

void add_Exception(Analyzer *analyzer, uint32_t line, char *message)
{
    Exception ex;
    ex.line = line;
    ex.message = strdup(message);

    analyzer->exceptions[exceptions_pos++] = ex;
}

void write_TS_ID(Analyzer *analyzer) {
    FILE *f = fopen("TS_ID.csv", "w");

    fprintf(f, "ID,Position\n");

    hti iterator = ht_iterator(analyzer->TS_ID);

    while (ht_next(&iterator)) {
        fprintf(f, "%s,%d\n", iterator.key, *(uint32_t*) iterator.value);
    }
    
    fclose(f);
}

void write_TS_CONST(Analyzer *analyzer) {
    FILE *f = fopen("TS_CONST.csv", "w");

    fprintf(f, "CONST,Position\n");

    hti iterator = ht_iterator(analyzer->TS_CONST);

    while (ht_next(&iterator)) {
        fprintf(f, "%s,%d\n", iterator.key, *(uint32_t*) iterator.value);
    }
    
    fclose(f);
}

void write_FIP(Analyzer *analyzer) {
    FILE *f = fopen("FIP.csv", "w");

    fprintf(f, "Keyword ID,Keyword,TS Position\n");

    for (int i = 0; i < fip_pos; i++) {
        fprintf(f, "%d,%s,%d\n", analyzer->FIP[i].keyword_id, analyzer->FIP[i].keyword, analyzer->FIP[i].ts_pos);
    }
    
    fclose(f);
}

void write_Exceptions(Analyzer *analyzer) {
    FILE *f = fopen("exceptions.csv", "w");

    fprintf(f, "Line,Message\n");

    for (int i = 0; i < exceptions_pos; i++) {
        fprintf(f, "%d,%s\n", analyzer->exceptions[i].line, analyzer->exceptions[i].message);
    }
    
    fclose(f);
}

void init(Analyzer *analyzer) {
    analyzer->TS_ID = ht_create();
    analyzer->TS_CONST = ht_create();
    analyzer->FIP = (FIP_Entry*) malloc(1024 * sizeof(FIP_Entry));
    analyzer->exceptions = (Exception*) malloc(1024 * sizeof(Exception));
}

void destroy(Analyzer *analyzer) {
    ht_destroy(analyzer->TS_ID);
    ht_destroy(analyzer->TS_CONST);

    // freeing exceptions
    for (int i = 0; i < exceptions_pos; i++) {
        free(analyzer->exceptions[i].message);
    }

    free(analyzer->FIP);
    free(analyzer->exceptions);
}
#line 825 "flexer.c"
#line 826 "flexer.c"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 173 ".\\flexer.l"


#line 1102 "flexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 166 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 402 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 45 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 45 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 46 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 175 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 3;
    const char* keyword = "int";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return INT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 184 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 4;
    const char* keyword = "float";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return FLOAT;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 193 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 5;
    const char* keyword = "string";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return STRING;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 202 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 6;
    const char* keyword = "struct";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return STRUCT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 211 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 7;
    const char* keyword = "if";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return IF;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 220 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 8;
    const char* keyword = "else";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return ELSE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 229 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 9;
    const char* keyword = "for";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return FOR;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 10;
    const char* keyword = "var";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return VAR;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 247 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 11;
    const char* keyword = "func";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return FUNC;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 256 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 12;
    const char* keyword = "main";
    
    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return MAIN;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 265 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 13;
    const char* keyword = "fmt.Scan";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return SCAN;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 274 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 14;
    const char* keyword = "fmt.Print";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return PRINT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 283 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 15;
    const char* keyword = "fmt.Println";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return PRINTLN;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 292 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 16;
    const char* keyword = "cattimp";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return CATTIMP;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 301 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 17;
    const char* keyword = "==";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return EQ;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 310 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 18;
    const char* keyword = "!=";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return NEQ;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 319 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 19;
    const char* keyword = "<";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return LT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 328 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 20;
    const char* keyword = "<=";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return LTE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 337 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 21;
    const char* keyword = ">";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);    
    return GT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 346 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 22;
    const char* keyword = ">=";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return GTE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 355 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 23;
    const char* keyword = "=";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return ASSIGN;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 364 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 24;
    const char* keyword = ":=";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return DECLARE;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 373 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 25;
    const char* keyword = "+";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return PLUS;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 382 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 26;
    const char* keyword = "-";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return MINUS;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 391 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 27;
    const char* keyword = "*";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return MUL;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 400 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 28;
    const char* keyword = "/";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return DIV;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 409 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 29;
    const char* keyword = "%";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return MOD;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 418 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 30;
    const char* keyword = "(";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return LPAREN;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 427 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 31;
    const char* keyword = ")";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return RPAREN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 436 ".\\flexer.l"
{
    lastTokenWasSeparator = true;
    int keyword_id = 32;
    const char* keyword = "{";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);    
    return LBRACE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 445 ".\\flexer.l"
{
    lastTokenWasSeparator = true;
    int keyword_id = 33;
    const char* keyword = "}";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return RBRACE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 454 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 34;
    const char* keyword = "[";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return LBRACKET;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 463 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 35;
    const char* keyword = "]";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return RBRACKET;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 472 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 36;
    const char* keyword = ",";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return COMMA;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 481 ".\\flexer.l"
{
    lastTokenWasSeparator = true;
    int keyword_id = 37;
    const char* keyword = "stop";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return STOP;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 490 ".\\flexer.l"
{
    lastTokenWasSeparator = true;
    int keyword_id = 38;
    const char* keyword = "executa";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return EXECUTA;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 499 ".\\flexer.l"
{
    lastTokenWasSeparator = true;
    int keyword_id = 39;
    const char* keyword = "sfcattimp";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return SFCATTIMP;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 508 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 40;
    const char* keyword = "&";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return AMPERSAND;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 517 ".\\flexer.l"
{
    lastTokenWasSeparator = false;
    int keyword_id = 41;
    const char* keyword = "elif";

    add_FIP_Entry(analyzer, keyword_id, keyword, &ts_pos);
    return ELIF;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 526 ".\\flexer.l"
{
    add_TS_ID(analyzer, yytext, &ts_id);

    const char* keyword = strdup(yytext);
    add_FIP_Entry(analyzer, 0, keyword, &ts_id);
    return ID;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 534 ".\\flexer.l"
{
    add_TS_CONST(analyzer, yytext, &ts_const);

    const char* keyword = strdup(yytext);
    add_FIP_Entry(analyzer, 1, keyword, &ts_const);
    return CONST;
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 542 ".\\flexer.l"
{
    if (!lastTokenWasSeparator) {
        char* ex = (char*) malloc(128 * sizeof(char));
        sprintf(ex, "Line did not end with a separator!");
        add_Exception(analyzer, currLine, ex);
        hasErrors = 1;
    }
    lastTokenWasSeparator = false;
    currLine++;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 553 ".\\flexer.l"
;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 555 ".\\flexer.l"
{
    lastTokenWasSeparator = false;

    char* ex = (char*) malloc(128 * sizeof(char));
    sprintf(ex, "Unknown token %s", yytext);
    add_Exception(analyzer, currLine, ex);
    hasErrors = 1;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 564 ".\\flexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1709 "flexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 166 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 166 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 165);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 564 ".\\flexer.l"

